### ISSUE TITLE
Make types run in puppet 4

### ISSUE THREAD

**Issue by ITler** [voxpupuli/puppet-zabbix#182]
Hello,

I've got a fresh Ubuntu14LTS 64bit dev box with installed puppet agent from puppetlabs PC1 (bundled installation containing ruby) offical repository.
Currently, this package delivers
- `puppet --version` 4.3.2
- `/opt/puppetlabs/puppet/bin/ruby -v` 2.1.8p440
- `/opt/puppetlabs/puppet/bin/gem -v` 2.2.5

On this dev node, I install _zabbix server_ (single node installation) and _javagateway_ following your instruction. Works fine so far.
Additionally, I want puppet to define a hostgroup after _zabbix server_ is bootstrapped doing:

```
zabbix_hostgroup { 'mygroup': }
```

So this is done somewhere in my manifests that are running on zabbix server node. Therefore I enabled `manage_resources` in hiera by setting zabbix _params_:  `zabbix::params::manage_resources: true`
### First issue

This is non-working with puppet 4, because puppet can't find required file in `type/zabbix_hostgroup.rb`

Adding `$LOAD_PATH.unshift(File.join(File.dirname(__FILE__),"..",".."))` as first line in code will solve this for puppet 4 and should have no negative impact to puppet versions prior to 4. (See #181)
### Second issue

This issue occured: `cannot load such file -- zabbixapi`

For tracking the issue, I've tried to manually install _ruby_ and all dependencies...
- upstream ruby `ruby -v` 1.9.3p484
- upstream gem `gem -v` 1.8.23

...to make `gem install zabbixapi` work.
Then I re-run puppet but still got `cannot load such file -- zabbixapi` error. This proves puppet only knows the bundled ruby, so installing _zabbixapi_ gem is supposed to happen in the bundled ruby.

This is done by doing

```
package { 'zabbixapi':
  provider => 'puppet_gem',
}
```
### Third issue

The next puppet run raises this issue:

```
Zabbix_hostgroup[mygroup]: Could not evaluate: undefined method `+' for nil:NilClass `
```

I've tried to use an older version (2.4.2) with no success. I've tried to `puppet [...] --debug` but I couldn't find additional information.

Now I need help as I do not know how to trigger down this issue as my ruby skills are limited.

I am depending on this to work.

Thank you
ITler

**Comment by dj-wasabi** [comment]
Hi @ITler 

For the first one: I accepted your PR, so this should be solved/working now.
2nd issue is same as #54 , but I don't have an solution for this now.
3rd issue: Could you give me the site-manifests file you are using?

Thank you.

**Comment by ITler** [comment]
I've been experimenting on how to get deployment of zabbix and my own configuration working.
The 3rd issue still persists, my config looks like that:

    class profiles::monitoring::aio {
      class { '::my_zabbix::profiles::aio': } # zabbix all in one aka. single node installation
      ->
      class { '::my_zabbix': } # my own configuration
    }

    class my_zabbix::profiles::aio {
      include ::my_zabbix::profiles::apache

      class { '::my_zabbix::profiles::postgres': }
      
      class { '::zabbix':
        # zabbix_url => $zabbix_url, # set via hiera to localhost
      }
      ->
      class { '::zabbix::javagateway': }

      # leaving this out lead to incomplete zabbix installation.
      # It looks like this forces all other classes (zabbix, postgres, apache) to run within this class (my_zabbix::profiles::aio).
      contain ::zabbix::javagateway 
    }

    # DEPENDENCIES
    ##############
    class my_zabbix::profiles::apache {
      class { '::apache':
          mpm_module => 'prefork',
      }
      include ::apache::mod::php
    }
    
    class my_zabbix::profiles::postgres(
      Variant[Undef,String] $listen_addresses = undef,
    ) {

      # I don't want to use upstream postgres (9.3)
      # Keeping all this out of config has no effect on the original issue, I'm describing
      unless defined(Class['Postgresql::Globals']) {
        class { '::postgresql::globals':
          encoding            => 'UTF-8',
          locale              => 'de_DE.UTF-8',
          manage_package_repo => true,
          version             => '9.4',
          before              => Class['postgresql::server'],
          # to force apt-get update after setting postgres repository and getting correct
          # order with apt::source['zabbix']
          notify              => Class['::apt::update'], 
        }
      }

      unless defined(Class['Postgresql::Server']) {
        class { '::postgresql::server':
          listen_addresses => $listen_addresses,
          require          => Class['::apt::update'], # to force apt-get update before installing postgres
        }
        class { '::postgresql::client':
          require          => Class['::apt::update'], # this is dependent due to ::postgresql::server
        }
      }

    }

    # OWN CONFIGURATION
    ###################
    
    class my_zabbix {
      class { '::my_zabbix::install': } ->
      Class['::my_zabbix']

      zabbix_hostgroup { 'failing': }
      
    }

    class my_zabbix::install {

      package { 'zabbixapi':
        provider => 'puppet_gem', # to use puppet 4.x bundled ruby and gem (as upstream ruby not available)
      }
    }

The 3rd issue persists even when calling puppet multiple times. Generally, zabbix installation works.

**Comment by ITler** [comment]
@dj-wasabi Regarding 3rd issue, I've implemented another solution for me (work-around). I just don't use `zabbix_hostgroup`. We could close this issue, as my workaround allows me to do what I need to do, although the problem described here is not solved. Your call.

Thank you

**Comment by baurmatt** [comment]
@ITler/@bastelfreak can you close it? :)

**Comment by ITler** [comment]
I'm out of this, as the use-case is not relevant for me anymore. 2,5years..
